language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DEVELOPMENT=true
        - HOSTNAME='0.0.0.0'
        - IP='0.0.0.0'
        - PORT='5000'
        - SECRET_KEY="whatever" 
install: "pip3 install -r requirements.txt"
script:
  python3 manage.py test || python manage.py test